### ISSUE TITLE
Flawed logic in the Python example

### ISSUE THREAD

**Issue by lanurmi** [jhasse/clicolors#2]
The `has_colors()` function in the Python example contains undesirable, flawed logic. If neither of the two environment variables is set, then the return value is `False`. I don't think the goal is to enable colors only when such variables are set to something.

The return value should depend on `isatty()`'s return value when neither variable exists.

**Comment by jhasse** [comment]
The reason for this was that Windows still doesn't support ANSI color escapes out of the box (have to be enabled with a WinAPI call).

But it's 2018 and Windows should have an incentive to change this. I've modified the example so that the first `getenv` call returns True, if `CLICOLOR` isn't defined.

**Comment by lanurmi** [comment]
Ah, Windows. Still, IMHO better to do the right thing (as the modified example now does) on *nix and handle Windows as a special case in programs where Windows is even relevant.
